/**
 * zh overlay — machine-assisted translations, reviewed before merge.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * Kept separate from the mn/en dictionary on purpose. The source files are
 * hand-authored and a machine should not rewrite them; keeping the generated
 * text in one file per language also means a human translator can be handed
 * exactly one file, and a bad run can be thrown away wholesale.
 */
export const zh: Record<string, string> = {};
